src/WebimpressCodingStandard/Sniffs/Commenting/PlacementSniff.php, test/Sniffs/Commenting/PlacementUnitTest.inc, test/Sniffs/Commenting/PlacementUnitTest.inc.fixed, test/Sniffs/Commenting/PlacementUnitTest.php
Fixed false positive when space was required before comment which was after php open tag.
=> Comment Placement sniff - allow comments in the first column after PHP opening tag

src/WebimpressCodingStandard/Sniffs/Commenting/DocCommentSniff.php, test/Sniffs/Commenting/DocCommentUnitTest.inc, test/Sniffs/Commenting/DocCommentUnitTest.inc.fixed
Blank line shouldn't be required before doc-block in array (when on the top) or when in function call. See test for more details.
=> DocComment sniff - do not require blank line before doc comment when in array or function call

src/WebimpressCodingStandard/Sniffs/Methods/LineAfterSniff.php, test/Sniffs/Methods/LineAfterUnitTest.inc, test/Sniffs/Methods/LineAfterUnitTest.inc.fixed, test/Sniffs/Methods/LineAfterUnitTest.php
Fixed adding empty line after method when the next content is doc-block.
Improvements in the sniffs to fix quicker.
=> LineAfter sniff - fixed case when next content is doc-block

src/WebimpressCodingStandard/Sniffs/PHP/DisallowFqnSniff.php
Fixes the issue when just imported class in DisalowFqn was removed in UnusedImport sniff
=> DisallowFqn - resolve conflict with UnusedImport sniff when imported class was removed

src/WebimpressCodingStandard/Sniffs/Formatting/RedundantParenthesesSniff.php, test/Sniffs/Formatting/RedundantParenthesesUnitTest.inc, test/Sniffs/Formatting/RedundantParenthesesUnitTest.inc.fixed
Fixes false-positive when class invoked with negation
/cc @weierophinney
=> RedundantParentheses sniff - false-positive when class invoked in statement

src/WebimpressCodingStandard/Sniffs/Formatting/StringClassReferenceSniff.php, test/Sniffs/Formatting/StringClassReferenceUnitTest.inc, test/Sniffs/Formatting/StringClassReferenceUnitTest.inc.fixed, test/Sniffs/Formatting/StringClassReferenceUnitTest.php
In PHP string backslash can be escaped. Tokenizer returns content with escape character so we need to replace drop these escape characters.
We can also return early when name contains spaces as it cannot be a valid class name.
=> StringClassReference sniff - better detection possible string classes

src/WebimpressCodingStandard/Sniffs/Namespaces/UnusedUseStatementSniff.php, test/Sniffs/Namespaces/UnusedUseStatementUnitTest.inc, test/Sniffs/Namespaces/UnusedUseStatementUnitTest.inc.fixed, test/Sniffs/Namespaces/UnusedUseStatementUnitTest.php
False-positive when imported class used in annotations was marked as unused and removed by `Namespaces\UnusedUseStatement` sniff.
=> UnusedUseStatement sniff - better recognise classes in doc-block annotations

src/WebimpressCodingStandard/Sniffs/Formatting/StringClassReferenceSniff.php, test/Sniffs/Formatting/StringClassReferenceUnitTest.inc, test/Sniffs/Formatting/StringClassReferenceUnitTest.inc.fixed
Before we had wrong regular expression to match FQCN and because of that the sniff may work incorrectly.
=> StringClassReference - fixed regular expression to match FQCN

src/WebimpressCodingStandard/CodingStandard.php, src/WebimpressCodingStandard/Sniffs/Namespaces/UnusedUseStatementSniff.php, src/WebimpressCodingStandard/Sniffs/PHP/CorrectClassNameCaseSniff.php, src/WebimpressCodingStandard/Sniffs/PHP/DisallowFqnSniff.php, test/Sniffs/Namespaces/UnusedUseStatementUnitTest.inc, test/Sniffs/Namespaces/UnusedUseStatementUnitTest.inc.fixed, test/Sniffs/PHP/CorrectClassNameCaseUnitTest.1.inc, test/Sniffs/PHP/CorrectClassNameCaseUnitTest.1.inc.fixed, test/Sniffs/PHP/CorrectClassNameCaseUnitTest.php, test/Sniffs/PHP/DisallowFqnUnitTest.3.inc, test/Sniffs/PHP/DisallowFqnUnitTest.3.inc.fixed, test/Sniffs/PHP/DisallowFqnUnitTest.php
Support has been added to the followin sniffs:
- `Namespaces\UnusedUseStatement`
- `PHP\CorrectClassNameCase`
- `PHP\DisallowFqn`
Includes unit tests.
=> Adds support for `@method` tag

src/WebimpressCodingStandard/Helper/MethodsTrait.php, src/WebimpressCodingStandard/Sniffs/Functions/ParamSniff.php, test/Sniffs/Commenting/TagWithTypeUnitTest.inc, test/Sniffs/Functions/ParamUnitTest.1.inc, test/Sniffs/Functions/ParamUnitTest.php, test/Sniffs/Functions/ReturnTypeUnitTest.inc
Regular expression was used in the following sniffs:
- `Commenting\TagWithType`
- `Functions\Param`
- `Functions\ReturnType`
Unit tests included.
=> Fixes regular expression to check class name

src/WebimpressCodingStandard/Sniffs/Functions/ReturnTypeSniff.php, test/Sniffs/Functions/ReturnTypeUnitTest.inc
Handle boolean expression and yoda comparisons within return statement
=> Functions\ReturnType - better recognise returned value

src/WebimpressCodingStandard/Sniffs/PHP/CorrectClassNameCaseSniff.php, src/WebimpressCodingStandard/Sniffs/PHP/DisallowFqnSniff.php, test/Sniffs/PHP/CorrectClassNameCaseUnitTest.inc, test/Sniffs/PHP/CorrectClassNameCaseUnitTest.inc.fixed, test/Sniffs/PHP/DisallowFqnUnitTest.inc, test/Sniffs/PHP/DisallowFqnUnitTest.inc.fixed
Affected sniffs:
- `PHP\CorrectClassNameCase`
- `PHP\DisallowFqn`
=> Fixes issue with invalid type in PHPDoc - fixer infinite loop

CHANGELOG.md, src/WebimpressCodingStandard/Sniffs/Classes/AlphabeticallySortedTraitsSniff.php, src/WebimpressCodingStandard/Sniffs/Namespaces/AlphabeticallySortedUsesSniff.php, test/Sniffs/Classes/AlphabeticallySortedTraitsUnitTest.inc, test/Sniffs/Classes/AlphabeticallySortedTraitsUnitTest.inc.fixed, test/Sniffs/Namespaces/AlphabeticallySortedUsesUnitTest.inc, test/Sniffs/Namespaces/AlphabeticallySortedUsesUnitTest.inc.fixed
Affected sniffs:
- `Classes\AlphabeticallySortedTraits`
- `Namespaces\AlphabeticallySortedUses`
Fixes #32
=> Fixes sorting class names (global import, traits)

src/WebimpressCodingStandard/Sniffs/PHP/CorrectClassNameCaseSniff.php, test/Integration/NoNamespaceImport.php, test/Integration/NoNamespaceImport.php.fixed
In case of file without namespace, when we have imported class and also used the same class with fcqn in the file (without leading `\`) import was removed and fcqn was replaced with the imported name. It leads to invalid class name in the file. Only import should be removed.
=> Fix invalid fixer behaviour (no namespace, imported class, fcqn)

src/WebimpressCodingStandard/Helper/NamespacesTrait.php, src/WebimpressCodingStandard/Sniffs/Classes/AlphabeticallySortedTraitsSniff.php, src/WebimpressCodingStandard/Sniffs/Commenting/CodingStandardTagsSniff.php, src/WebimpressCodingStandard/Sniffs/Commenting/FunctionCommentSniff.php, src/WebimpressCodingStandard/Sniffs/Commenting/FunctionDisallowedTagSniff.php, src/WebimpressCodingStandard/Sniffs/Commenting/TagWithTypeSniff.php, src/WebimpressCodingStandard/Sniffs/Commenting/VariableCommentSniff.php, src/WebimpressCodingStandard/Sniffs/Files/DeclareStrictTypesSniff.php, src/WebimpressCodingStandard/Sniffs/PHP/StaticCallbackSniff.php, test/Sniffs/PHP/StaticCallbackUnitTest.inc, test/Sniffs/PHP/StaticCallbackUnitTest.inc.fixed, test/Sniffs/PHP/StaticCallbackUnitTest.php
When `$this` is not used within the closure context, callback can be set as `static`.
=> Feature: PHP\StaticCallback sniff

src/WebimpressCodingStandard/Sniffs/PHP/DisallowCurlyOffsetAccessBraceSniff.php, test/Sniffs/PHP/DisallowCurlyOffsetAccessBraceUnitTest.inc, test/Sniffs/PHP/DisallowCurlyOffsetAccessBraceUnitTest.inc.fixed, test/Sniffs/PHP/DisallowCurlyOffsetAccessBraceUnitTest.php
As of PHP 7.4:
> the array and string offset access syntax using curly braces is deprecated.
=> Feature: PHP\DisallowCurlyOffsetAccessBrace sniff

src/WebimpressCodingStandard/Sniffs/ControlStructures/DefaultAsLastSniff.php, test/Sniffs/ControlStructures/DefaultAsLastUnitTest.inc, test/Sniffs/ControlStructures/DefaultAsLastUnitTest.php
The `default` case should be as the last case in `switch`.
=> Feature: ControlStructures\DefaultAsLast

src/WebimpressCodingStandard/Helper/MethodsTrait.php, src/WebimpressCodingStandard/Sniffs/NamingConventions/ValidVariableNameSniff.php, src/WebimpressCodingStandard/ruleset.xml, test/Sniffs/NamingConventions/ValidVariableNameUnitTest.inc, test/Sniffs/NamingConventions/ValidVariableNameUnitTest.php
Defined variables, variables used in strings and class properties must
be now camelCased (strict) - so two capital letters next to each other
are not allowed
Disable `PSR2.Classes.PropertyDeclaration.Underscore` as it is now covered
in `Webimpress\NamingConventions\ValidVariableName` sniff.
=> Feature: all variables must be camel case - strict

src/WebimpressCodingStandard/ruleset.xml
Sniff `Generic.NamingConventions.CamelCapsFunctionName` requires function and method names to be in camelCase format (strict)
=> Feature: replace PSR1.Methods.CamelCapsMethodName with Generic.Naming Conventions.CamelCapsFunctionName

src/WebimpressCodingStandard/Sniffs/Commenting/TagNameSniff.php, src/WebimpressCodingStandard/Sniffs/WhiteSpace/CommaSpacingSniff.php, test/Sniffs/Commenting/TagNameUnitTest.inc, test/Sniffs/Commenting/TagNameUnitTest.inc.fixed, test/Sniffs/Commenting/TagNameUnitTest.php
Check tags if there are any disallowed characters at the end of the name.
By defualt configured with `:` and `;` but can be set to any charactes
by configuration option `disallowedEndChars`.
=> Feature: Commenting\TagName sniff

src/WebimpressCodingStandard/Helper/MethodsTrait.php, src/WebimpressCodingStandard/Sniffs/Commenting/TagWithTypeSniff.php, test/Sniffs/Commenting/TagWithTypeUnitTest.3.inc, test/Sniffs/Commenting/TagWithTypeUnitTest.3.inc.fixed, test/Sniffs/Commenting/TagWithTypeUnitTest.php
Added configuration option `nullPosition` with default value `first`.
The other allowed value is `last` so then `null` is going to be at the end of types list.
=> Feature: Commenting\TagWithType ability to configure null to be at the end

src/WebimpressCodingStandard/Sniffs/Commenting/DisallowEmptyCommentSniff.php, test/Sniffs/Commenting/DisallowEmptyCommentUnitTest.inc, test/Sniffs/Commenting/DisallowEmptyCommentUnitTest.inc.fixed, test/Sniffs/Commenting/DisallowEmptyCommentUnitTest.php
Detects empty comments (doc-blocks, multiline and inline comments) and redundant empty lines in comments.
Two empty lines next to each other are disallowed, also - empty lines at the beginning and at the end of the comment are disallowed.
=> Feature: Commenting\DisallowEmptyComment sniff

src/WebimpressCodingStandard/Sniffs/Commenting/DocCommentSniff.php, test/Sniffs/Commenting/DocCommentUnitTest.inc, test/Sniffs/Commenting/DocCommentUnitTest.inc.fixed, test/Sniffs/Commenting/DocCommentUnitTest.php
Additional asterisk with open and close PHPDoc tags are not allowed.
Fixer replace invalid tags with short version - `/**`/`*/`.
=> Feature: Commenting\DocComment - checks PHPDoc open and close tags

src/WebimpressCodingStandard/Sniffs/Arrays/FormatSniff.php, test/Sniffs/Arrays/FormatUnitTest.inc, test/Sniffs/Arrays/FormatUnitTest.inc.fixed, test/Sniffs/Arrays/FormatUnitTest.php
Using comment before arrow in array is disallowed.
Additional empty lines before arrow in array are disallowed.
Fixes also issue when empty line was not removed before the value.
=> Feature: Array\Format - disallow comments and blank lines before arrows

src/WebimpressCodingStandard/Sniffs/Namespaces/AlphabeticallySortedUsesSniff.php, test/Sniffs/Namespaces/AlphabeticallySortedUsesUnitTest.2.inc, test/Sniffs/Namespaces/AlphabeticallySortedUsesUnitTest.2.inc.fixed, test/Sniffs/Namespaces/AlphabeticallySortedUsesUnitTest.php
Before this sniff worked only on files with namespaces.
We'd like to sort imports also in files without namespace defined.
=> Hotfix: Namespaces\AlphabeticallySortedUses - sort uses also in files without namespace

src/WebimpressCodingStandard/Sniffs/Namespaces/UniqueImportSniff.php, test/Sniffs/Namespaces/UniqueImportUnitTest.1.inc, test/Sniffs/Namespaces/UniqueImportUnitTest.2.inc, test/Sniffs/Namespaces/UniqueImportUnitTest.inc, test/Sniffs/Namespaces/UniqueImportUnitTest.php
Check if the class/function/constant is imported only once.
Check if the name is used only once.
The same name can be used for class, function and constant.
Class and function names are case insensitive, constant names are case sensitive, and also namespaces are case sensitive.
=> Feature: Namespaces\UniqueImport sniff

src/WebimpressCodingStandard/Helper/AnnotationsTrait.php, test/Sniffs/Commenting/ClassAnnotationUnitTest.3.inc, test/Sniffs/Commenting/ClassAnnotationUnitTest.php, test/Sniffs/Commenting/MethodAnnotationUnitTest.1.inc, test/Sniffs/Commenting/MethodAnnotationUnitTest.2.inc, test/Sniffs/Commenting/MethodAnnotationUnitTest.inc, test/Sniffs/Commenting/MethodAnnotationUnitTest.php, test/Sniffs/Commenting/PropertyAnnotationUnitTest.1.inc, test/Sniffs/Commenting/PropertyAnnotationUnitTest.2.inc, test/Sniffs/Commenting/PropertyAnnotationUnitTest.inc, test/Sniffs/Commenting/PropertyAnnotationUnitTest.php
- `Commenting\ClassAnnotation` sniff - `final` classes.
- `Commenting\MethodAnootation` sniff - `final` methods.
- `Commenting\PropertyAnnotation` sniff - properties defined with `var`.
=> Hotfix: adds missing modifiers in Annotation sniffs

src/WebimpressCodingStandard/Sniffs/Commenting/TagWithTypeSniff.php, src/WebimpressCodingStandard/Sniffs/Functions/ParamSniff.php, test/Sniffs/Commenting/TagWithTypeUnitTest.1.inc, test/Sniffs/Commenting/TagWithTypeUnitTest.1.inc.fixed, test/Sniffs/Commenting/TagWithTypeUnitTest.3.inc, test/Sniffs/Commenting/TagWithTypeUnitTest.3.inc.fixed, test/Sniffs/Commenting/TagWithTypeUnitTest.php, test/Sniffs/Functions/ParamUnitTest.inc, test/Sniffs/Functions/ParamUnitTest.inc.fixed, test/Sniffs/Functions/ParamUnitTest.php, test/Sniffs/Functions/ReturnTypeUnitTest.1.inc, test/Sniffs/Functions/ReturnTypeUnitTest.1.inc.fixed, test/Sniffs/Functions/ReturnTypeUnitTest.php, test/Sniffs/Functions/ThrowsUnitTest.inc, test/Sniffs/Functions/ThrowsUnitTest.inc.fixed
Split on string was done incorrectly, as it assumed always one white character, where we can have multiple spaces (in case variable names are aligned in PHPDocs).
Fixed how we split the string, so we can get better results on reporting errors and fixing.
=> Hotfix: parsing `@param` and `@var` PHPDoc tags with multiple spaces

src/WebimpressCodingStandard/Sniffs/Classes/TraitUsageSniff.php, test/Sniffs/Classes/TraitUsageUnitTest.inc, test/Sniffs/Classes/TraitUsageUnitTest.inc.fixed, test/Sniffs/Classes/TraitUsageUnitTest.php
We cannot have any other properties, constants, methods... defined before traits in classes/traits.
=> Feature: Classes\TraitUsage - checks if traits are defined on top of the class

src/WebimpressCodingStandard/Sniffs/Classes/PropertyBeforeMethodSniff.php, test/Sniffs/Classes/PropertyBeforeMethodUnitTest.inc, test/Sniffs/Classes/PropertyBeforeMethodUnitTest.inc.fixed, test/Sniffs/Classes/PropertyBeforeMethodUnitTest.php
Class properties should be defined before class methods.
=> Feature: Classes\PropertyBeforeMethod sniff

src/WebimpressCodingStandard/Sniffs/Commenting/DocCommentSniff.php, test/Sniffs/Commenting/DocCommentUnitTest.inc, test/Sniffs/Commenting/DocCommentUnitTest.inc.fixed, test/Sniffs/Commenting/DocCommentUnitTest.php
Doc-block comment should have a star at the beginning of every line:
```php
/**
* comment
*/
```
And the following example is invalid:
```php
/**
comment
*/
```
=> Feature: Commenting\DocComment sniff checks if there is a star in every line

src/WebimpressCodingStandard/Sniffs/Namespaces/UnusedUseStatementSniff.php, test/Sniffs/Namespaces/UnusedUseStatementUnitTest.1.inc, test/Sniffs/Namespaces/UnusedUseStatementUnitTest.1.inc.fixed, test/Sniffs/Namespaces/UnusedUseStatementUnitTest.3.inc, test/Sniffs/Namespaces/UnusedUseStatementUnitTest.3.inc.fixed, test/Sniffs/Namespaces/UnusedUseStatementUnitTest.inc, test/Sniffs/Namespaces/UnusedUseStatementUnitTest.inc.fixed, test/Sniffs/Namespaces/UnusedUseStatementUnitTest.php
Adds support for use groups, various fixes on detecting if imported class/function/const is used in the code.
The same alias can be used for class, function and constant, so we need to detect what is the context of the string token.
For classes and function PHP is case insensitive, but not for constants. So we can have defined/imported constants with names: `FOO`, `Foo`, `foo` and all these three are different.
=> Feature: Namespaces\UnusedUseStatement - support for use groups + fixes

src/WebimpressCodingStandard/Sniffs/WhiteSpace/OperatorAndKeywordSpacingSniff.php, src/WebimpressCodingStandard/ruleset.xml, test/Sniffs/WhiteSpace/OperatorAndKeywordSpacingUnitTest.inc, test/Sniffs/WhiteSpace/OperatorAndKeywordSpacingUnitTest.inc.fixed, test/Sniffs/WhiteSpace/OperatorAndKeywordSpacingUnitTest.php
Replaces `Squiz.WhiteSpace.OperatorSpacing` as it was not possible to
configure to force space after (and before) some tokens only.
It still extends `Squiz.WhiteSpace.OperatorSpacing` but works also with
some PHP keywords (`as`, `insteadof`) and force one space before and after:
- `as`
- `insteadof`
- `instanceof`
Also, this new sniff allow only ONE empty line before operator,
and disallow empty line after opertator.
In case operator is at the end of the line it will be moved to next line
just before the non-empty content with single space.
=> Feature: WhiteSpace\OperatorAndKeywordSpacing sniff

src/WebimpressCodingStandard/Sniffs/Functions/ParamSniff.php, src/WebimpressCodingStandard/Sniffs/Functions/ReturnTypeSniff.php, test/Sniffs/Functions/ParamUnitTest.1.inc, test/Sniffs/Functions/ParamUnitTest.php, test/Sniffs/Functions/ReturnTypeUnitTest.2.inc, test/Sniffs/Functions/ReturnTypeUnitTest.2.inc.fixed, test/Sniffs/Functions/ReturnTypeUnitTest.3.inc, test/Sniffs/Functions/ReturnTypeUnitTest.php
Generators (functions with yield) can have only:
`Generator`, `Iterator`, `Traversable` or `iterable` return type hint.
Add support for Iterator type in `Functions\Param` and `Functions\ReturnType` sniffs.
=> Add Iterator type support + fixes for functions with yield

src/WebimpressCodingStandard/Sniffs/Arrays/DoubleArrowSniff.php, src/WebimpressCodingStandard/Sniffs/WhiteSpace/ScopeIndentSniff.php, test/Integration/AlignOperators.php, test/Integration/AlignOperators.php.fixed, test/Integration/AlignOperators.xml, test/IntegrationTest.php, test/Sniffs/Arrays/DoubleArrowUnitTest.1.inc.fixed, test/Sniffs/Arrays/DoubleArrowUnitTest.2.inc, test/Sniffs/Arrays/DoubleArrowUnitTest.2.inc.fixed, test/Sniffs/Arrays/DoubleArrowUnitTest.inc, test/Sniffs/Arrays/DoubleArrowUnitTest.inc.fixed, test/Sniffs/Arrays/DoubleArrowUnitTest.php
To configure that we need to set (for example):
```
// configuration of double arrow alignment
WebimpressCodingStandard.Arrays.DoubleArrow.maxPadding = 50
WebimpressCodingStandard.Arrays.DoubleArrow.ignoreNewLineArrayArrow = false
// ignore indent or double arrow when at the beggining of the line
WebimpressCodingStandard.WhiteSpace.ScopeIndent.ignoreNewLineArrayArrow = true
// ignore spacing before double arrow (so we can have more than one space)
WebimpressCodingStandard.WhiteSpace.OperatorAndKeywordSpacing.ignoreSpacingBeforeAssignments = true
```
Fixes #29
=> Feature: ability to align array arrows when in new line

src/WebimpressCodingStandard/Sniffs/Namespaces/AlphabeticallySortedUsesSniff.php, test/Sniffs/Namespaces/AlphabeticallySortedUsesUnitTest.inc, test/Sniffs/Namespaces/AlphabeticallySortedUsesUnitTest.inc.fixed, test/Sniffs/Namespaces/AlphabeticallySortedUsesUnitTest.php
If use statement is below some additional content (for example class
definition) it has been removed on sorting.
=> Hotfix: Namespaces\AlphabeticallySortedUses do not remove content

src/WebimpressCodingStandard/Sniffs/Classes/NoNullValuesSniff.php, test/Sniffs/Classes/NoNullValuesUnitTest.inc, test/Sniffs/Classes/NoNullValuesUnitTest.inc.fixed, test/Sniffs/Classes/NoNullValuesUnitTest.php, test/Sniffs/Commenting/PropertyAnnotationUnitTest.1.inc, test/Sniffs/Commenting/PropertyAnnotationUnitTest.2.inc
Since PHP 7.4 we can define property type. In that case, when property
is defined with nullable type we can have default null value, as it is
different from not being initialised.
Removed also invalid test case with callable property type, as it is not
valid in PHP 7.4.
Fixes #72
Also adds new code type for null values for properties with not-nullable
type declaration. This is technically invalid code.
/cc @shandyDev
=> Hotfix: allow null value for properties with nullable type declaration

src/WebimpressCodingStandard/Sniffs/PHP/DisallowFqnSniff.php, test/Sniffs/PHP/DisallowFqnUnitTest.inc, test/Sniffs/PHP/DisallowFqnUnitTest.inc.fixed, test/Sniffs/PHP/DisallowFqnUnitTest.php
Failing case:
```php
namespace A;
use B;
new B();
new \B\C();
```
Expected result:
```php
namespace A;
use B;
new B();
new B\C();
```
Actual result:
```php
namespace A;
use B;
new B();
new B();
```
=> Hotfix: PHP\DisallowFqn when namespace is already in use

CHANGELOG.md, src/WebimpressCodingStandard/Sniffs/PHP/ImportInternalConstantSniff.php, test/Sniffs/PHP/ImportInternalConstantUnitTest.inc, test/Sniffs/PHP/ImportInternalConstantUnitTest.inc.fixed, test/Sniffs/PHP/ImportInternalConstantUnitTest.php
If the previous token is `const` it's a constant declaration and not a usage of a PHP constant.
I'm not 100% sure if thats the right way to do it because it's first time I've looked into sniffs. Also, no idea how to write a test for that 🙂 
fixes #120
Edit: If it's not correct, just close the PR
Edit2: If you're fine with it, I'd be very thankful if you add the hacktoberfest label to it 🙃
=> Fixes importing class constant with global constant names

CHANGELOG.md, src/WebimpressCodingStandard/Sniffs/NamingConventions/ExceptionSniff.php, test/Integration/ExceptionWithNonExistingParent.php, test/Integration/ExceptionWithNonExistingParent.php.fixed
=> Fixes crash on NamingConventions\Exception sniff when parent class does not exist

CHANGELOG.md, composer.json, composer.lock, src/WebimpressCodingStandard/Sniffs/ControlStructures/DefaultAsLastSniff.php, src/WebimpressCodingStandard/Sniffs/ControlStructures/RedundantCaseSniff.php, src/WebimpressCodingStandard/Sniffs/Formatting/RedundantParenthesesSniff.php, src/WebimpressCodingStandard/Sniffs/PHP/RedundantSemicolonSniff.php, test/Sniffs/ControlStructures/DefaultAsLastUnitTest.inc, test/Sniffs/ControlStructures/RedundantCaseUnitTest.inc, test/Sniffs/ControlStructures/RedundantCaseUnitTest.inc.fixed, test/Sniffs/Formatting/RedundantParenthesesUnitTest.inc, test/Sniffs/Formatting/RedundantParenthesesUnitTest.inc.fixed, test/Sniffs/PHP/RedundantSemicolonUnitTest.inc, test/Sniffs/PHP/RedundantSemicolonUnitTest.inc.fixed
- ControlStructures\DefaultAsLastSniff
- ControlStructures\RedundantCaseSniff
- Formatting\RedundantParenthesesSniff
- PHP\RedundantSemicolonSniff
Requires PHP_CodeSniffer release to get it working on pre PHP 8.
=> Fixes for PHP 8 match expression

src/WebimpressCodingStandard/Sniffs/Formatting/ReturnTypeSniff.php, test/Sniffs/Formatting/ReturnTypeUnitTest.inc, test/Sniffs/Formatting/ReturnTypeUnitTest.inc.fixed, test/Sniffs/Formatting/ReturnTypeUnitTest.php
Allow the following Return types:
```php
function union(): bool|string;
function intersection(): Iterator&Countable;
function nullType(): null;
function boolFalse(): false;
function boolTrue(): true;
function unionAndIntersection(): string|(Iterator&Countable);
```
=> feat: Support union and intersection return types - Formatting\ReturnTypeSniff

src/WebimpressCodingStandard/Sniffs/Functions/ReturnTypeSniff.php, test/Sniffs/Functions/ReturnTypeUnitTest.inc
Case like 
```
public function insert(array $data): bool|mysqli_result
{
if (empty($data)) {
return false;
}
return new mysqli_result;
}
```
=> fix: Union return type (PHP 8.2) - Functions\ReturnTypeSniff

src/WebimpressCodingStandard/Sniffs/Formatting/RedundantParenthesesSniff.php, test/Sniffs/Formatting/RedundantParenthesesUnitTest.inc, test/Sniffs/Formatting/RedundantParenthesesUnitTest.inc.fixed
=> fix: Formatting\RedundantParentheses - closure with instanceof

src/WebimpressCodingStandard/Sniffs/WhiteSpace/OperatorAndKeywordSpacingSniff.php, test/Sniffs/WhiteSpace/OperatorAndKeywordSpacingUnitTest.1.inc, test/Sniffs/WhiteSpace/OperatorAndKeywordSpacingUnitTest.inc, test/Sniffs/WhiteSpace/OperatorAndKeywordSpacingUnitTest.inc.fixed, test/Sniffs/WhiteSpace/OperatorAndKeywordSpacingUnitTest.php
PR https://github.com/PHPCSStandards/PHP_CodeSniffer/pull/289 changes a lot around operator sniff, and now declare statement must be omitted (as it was done also for PSR-12 rule there). There is another sniff to verify declare statement, and we do not want to check it here.
=> fix: WhiteSpace\OperatorAndKeywordSpacingSniff - conflict with declare statement since PHP_CodeSniffer 3.9.1

composer.json, composer.lock, src/WebimpressCodingStandard/Sniffs/Formatting/ReturnTypeSniff.php
Since [PHP_CodeSniffer 3.10.0](https://github.com/PHPCSStandards/PHP_CodeSniffer/releases/tag/3.10.0) parenthesis token has been changed to:
- `T_TYPE_OPEN_PARENTHESIS` (from `T_OPEN_PARENTHESIS`)
- `T_TYPE_CLOSE_PARENTHESIS` (from `T_CLOSE_PARENTHESIS`)
and therefore the sniff did not work correctly for composite return type declarations.
Bump minimum PHP_CodeSniffer version to 3.10.3 so the new tokens are defined.
=> fix: Formatting\ReturnTypeSniff to use new type of token for parenthesis

src/WebimpressCodingStandard/Sniffs/PHP/DisallowFqnSniff.php, test/Sniffs/PHP/DisallowFqnUnitTest.inc, test/Sniffs/PHP/DisallowFqnUnitTest.inc.fixed, test/Sniffs/PHP/DisallowFqnUnitTest.php
Adds support for [DNF types](https://wiki.php.net/rfc/dnf_types) in PHP\Disallow\FqnSniff
=> feat: Support for DNF types in PHP\DisallowFqnSniff

src/WebimpressCodingStandard/Sniffs/Classes/NoNullValuesSniff.php, test/Sniffs/Classes/NoNullValuesUnitTest.inc, test/Sniffs/Classes/NoNullValuesUnitTest.inc.fixed
=> fix: Classes\NoNullValuesSniff for explicit nullable types

src/WebimpressCodingStandard/Sniffs/WhiteSpace/ScopeIndentSniff.php
Related issue https://github.com/squizlabs/PHP_CodeSniffer/issues/2748 has been merged and deployed, and we are now using version where the fix is present, so there is no longer need for the custom code, and it is removed now.
=> qa: Remove redundant code in WhiteSpace\ScopeIndentSniff as upstream is fixed
